// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies;

public enum CertificateType
{
	PublicKey("07b7812b-c7e4-4e58-8c00-75a89d74be84"),
	PrivateKey("bf984eaf-42e2-418d-9b87-95dca1f12213");

	private final java.lang.String i18nCaptionKey;
	
	private CertificateType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
