// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class AzureMetric implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject azureMetricMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.AzureMetric";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MetricName("MetricName"),
		MetricValue("MetricValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AzureMetric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AzureMetric(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject azureMetricMendixObject)
	{
		if (azureMetricMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!azureMetricMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.azureMetricMendixObject = azureMetricMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.AzureMetric initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.AzureMetric(context, mendixObject);
	}

	public static aiden_interfaces.proxies.AzureMetric load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.AzureMetric.initialize(context, mendixObject);
	}

	/**
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName()
	{
		return getMetricName(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricName
	 */
	public final java.lang.String getMetricName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MetricName.toString());
	}

	/**
	 * Set value of MetricName
	 * @param metricname
	 */
	public final void setMetricName(java.lang.String metricname)
	{
		setMetricName(getContext(), metricname);
	}

	/**
	 * Set value of MetricName
	 * @param context
	 * @param metricname
	 */
	public final void setMetricName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String metricname)
	{
		getMendixObject().setValue(context, MemberNames.MetricName.toString(), metricname);
	}

	/**
	 * @return value of MetricValue
	 */
	public final java.math.BigDecimal getMetricValue()
	{
		return getMetricValue(getContext());
	}

	/**
	 * @param context
	 * @return value of MetricValue
	 */
	public final java.math.BigDecimal getMetricValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MetricValue.toString());
	}

	/**
	 * Set value of MetricValue
	 * @param metricvalue
	 */
	public final void setMetricValue(java.math.BigDecimal metricvalue)
	{
		setMetricValue(getContext(), metricvalue);
	}

	/**
	 * Set value of MetricValue
	 * @param context
	 * @param metricvalue
	 */
	public final void setMetricValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal metricvalue)
	{
		getMendixObject().setValue(context, MemberNames.MetricValue.toString(), metricvalue);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return azureMetricMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.AzureMetric that = (aiden_interfaces.proxies.AzureMetric) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
