// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class CommonMetricData implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject commonMetricDataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.CommonMetricData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RegisteredAt("RegisteredAt"),
		LastFetchedAt("LastFetchedAt"),
		DurationMs("DurationMs"),
		Status("Status"),
		Count("Count"),
		OtherSystem("OtherSystem"),
		InterfaceName("InterfaceName"),
		FunctionName("FunctionName"),
		SyncType("SyncType"),
		EnvironmentType("EnvironmentType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CommonMetricData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CommonMetricData(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject commonMetricDataMendixObject)
	{
		if (commonMetricDataMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!commonMetricDataMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.commonMetricDataMendixObject = commonMetricDataMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.CommonMetricData initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.CommonMetricData(context, mendixObject);
	}

	public static aiden_interfaces.proxies.CommonMetricData load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.CommonMetricData.initialize(context, mendixObject);
	}

	/**
	 * @return value of RegisteredAt
	 */
	public final java.util.Date getRegisteredAt()
	{
		return getRegisteredAt(getContext());
	}

	/**
	 * @param context
	 * @return value of RegisteredAt
	 */
	public final java.util.Date getRegisteredAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RegisteredAt.toString());
	}

	/**
	 * Set value of RegisteredAt
	 * @param registeredat
	 */
	public final void setRegisteredAt(java.util.Date registeredat)
	{
		setRegisteredAt(getContext(), registeredat);
	}

	/**
	 * Set value of RegisteredAt
	 * @param context
	 * @param registeredat
	 */
	public final void setRegisteredAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date registeredat)
	{
		getMendixObject().setValue(context, MemberNames.RegisteredAt.toString(), registeredat);
	}

	/**
	 * @return value of LastFetchedAt
	 */
	public final java.util.Date getLastFetchedAt()
	{
		return getLastFetchedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of LastFetchedAt
	 */
	public final java.util.Date getLastFetchedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastFetchedAt.toString());
	}

	/**
	 * Set value of LastFetchedAt
	 * @param lastfetchedat
	 */
	public final void setLastFetchedAt(java.util.Date lastfetchedat)
	{
		setLastFetchedAt(getContext(), lastfetchedat);
	}

	/**
	 * Set value of LastFetchedAt
	 * @param context
	 * @param lastfetchedat
	 */
	public final void setLastFetchedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastfetchedat)
	{
		getMendixObject().setValue(context, MemberNames.LastFetchedAt.toString(), lastfetchedat);
	}

	/**
	 * @return value of DurationMs
	 */
	public final java.lang.Integer getDurationMs()
	{
		return getDurationMs(getContext());
	}

	/**
	 * @param context
	 * @return value of DurationMs
	 */
	public final java.lang.Integer getDurationMs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DurationMs.toString());
	}

	/**
	 * Set value of DurationMs
	 * @param durationms
	 */
	public final void setDurationMs(java.lang.Integer durationms)
	{
		setDurationMs(getContext(), durationms);
	}

	/**
	 * Set value of DurationMs
	 * @param context
	 * @param durationms
	 */
	public final void setDurationMs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer durationms)
	{
		getMendixObject().setValue(context, MemberNames.DurationMs.toString(), durationms);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final aiden_interfaces.proxies.ENUM_MetricStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final aiden_interfaces.proxies.ENUM_MetricStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_MetricStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(aiden_interfaces.proxies.ENUM_MetricStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_MetricStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of OtherSystem
	 */
	public final java.lang.String getOtherSystem()
	{
		return getOtherSystem(getContext());
	}

	/**
	 * @param context
	 * @return value of OtherSystem
	 */
	public final java.lang.String getOtherSystem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OtherSystem.toString());
	}

	/**
	 * Set value of OtherSystem
	 * @param othersystem
	 */
	public final void setOtherSystem(java.lang.String othersystem)
	{
		setOtherSystem(getContext(), othersystem);
	}

	/**
	 * Set value of OtherSystem
	 * @param context
	 * @param othersystem
	 */
	public final void setOtherSystem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String othersystem)
	{
		getMendixObject().setValue(context, MemberNames.OtherSystem.toString(), othersystem);
	}

	/**
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName()
	{
		return getInterfaceName(getContext());
	}

	/**
	 * @param context
	 * @return value of InterfaceName
	 */
	public final java.lang.String getInterfaceName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InterfaceName.toString());
	}

	/**
	 * Set value of InterfaceName
	 * @param interfacename
	 */
	public final void setInterfaceName(java.lang.String interfacename)
	{
		setInterfaceName(getContext(), interfacename);
	}

	/**
	 * Set value of InterfaceName
	 * @param context
	 * @param interfacename
	 */
	public final void setInterfaceName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String interfacename)
	{
		getMendixObject().setValue(context, MemberNames.InterfaceName.toString(), interfacename);
	}

	/**
	 * @return value of FunctionName
	 */
	public final java.lang.String getFunctionName()
	{
		return getFunctionName(getContext());
	}

	/**
	 * @param context
	 * @return value of FunctionName
	 */
	public final java.lang.String getFunctionName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FunctionName.toString());
	}

	/**
	 * Set value of FunctionName
	 * @param functionname
	 */
	public final void setFunctionName(java.lang.String functionname)
	{
		setFunctionName(getContext(), functionname);
	}

	/**
	 * Set value of FunctionName
	 * @param context
	 * @param functionname
	 */
	public final void setFunctionName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String functionname)
	{
		getMendixObject().setValue(context, MemberNames.FunctionName.toString(), functionname);
	}

	/**
	 * Get value of SyncType
	 * @param synctype
	 */
	public final aiden_interfaces.proxies.ENUM_MetricSyncType getSyncType()
	{
		return getSyncType(getContext());
	}

	/**
	 * @param context
	 * @return value of SyncType
	 */
	public final aiden_interfaces.proxies.ENUM_MetricSyncType getSyncType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SyncType.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_MetricSyncType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SyncType
	 * @param synctype
	 */
	public final void setSyncType(aiden_interfaces.proxies.ENUM_MetricSyncType synctype)
	{
		setSyncType(getContext(), synctype);
	}

	/**
	 * Set value of SyncType
	 * @param context
	 * @param synctype
	 */
	public final void setSyncType(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_MetricSyncType synctype)
	{
		if (synctype != null) {
			getMendixObject().setValue(context, MemberNames.SyncType.toString(), synctype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SyncType.toString(), null);
		}
	}

	/**
	 * Get value of EnvironmentType
	 * @param environmenttype
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironmentType()
	{
		return getEnvironmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EnvironmentType
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnvironmentType.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnvironmentType
	 * @param environmenttype
	 */
	public final void setEnvironmentType(aiden_interfaces.proxies.ENUM_Environment environmenttype)
	{
		setEnvironmentType(getContext(), environmenttype);
	}

	/**
	 * Set value of EnvironmentType
	 * @param context
	 * @param environmenttype
	 */
	public final void setEnvironmentType(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Environment environmenttype)
	{
		if (environmenttype != null) {
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), environmenttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EnvironmentType.toString(), null);
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return commonMetricDataMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.CommonMetricData that = (aiden_interfaces.proxies.CommonMetricData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
