// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricPropertyKey
{
	otherSystem("4a3deb7a-fceb-4fa9-adfe-88f9480d0cfa"),
	interfaceName("ed7f7e1e-813b-47fb-b978-2733bfc4908b"),
	syncType("d3fe9bdb-6208-4b88-b9bd-aab216927105"),
	functionName("6c8d8ac8-46e9-4d11-a009-7d4ffccdd9cc"),
	status("4e64a3dc-aec6-46fe-988a-e35d63505c40"),
	environment("22445bad-3b28-4dd2-b334-caf529b299d9"),
	applicationName("6c1f71fa-6f29-48a5-a710-8de6c4846f0c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricPropertyKey(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
