// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_ServiceType
{
	Rest("45934f36-60af-4e17-9f4b-e1428199c36b"),
	Soap("5a58a183-538f-4521-810b-be3aab2b533b"),
	OData("0a6daa78-8f6f-417b-809b-0488c714c25e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
