// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Host
{
	Username_Password("6d9d91b9-925f-4bef-a029-6a43849045bc"),
	Subscription_Key("a79ba691-f5a3-4afa-8e3b-c0d2062a9940"),
	User_Service_Settings("4ea27f52-567e-4911-bb2c-cfce32ec8cea"),
	OAuth("4df2c708-fed0-4c30-9e7a-b638167d9675"),
	Open("b2a6373e-8de9-41e5-b21d-a5d8a4711569");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Host(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
