// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_ServiceType
{
	Rest("a639d045-61e3-48ca-a1ed-d0e76adf3990"),
	Soap("2bca5a11-cb4f-4fb3-81a2-055e5f01c474"),
	OData("942c2e93-c575-4c20-b94c-26328613fc8c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
