// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Environment
{
	Development("0d7100b0-4eac-4c85-a18a-80a5db488f6b"),
	Test("60297680-755a-4adc-a61a-861e2fc8c58d"),
	Acceptance("1b36b908-e3fd-4c0c-b3e3-ad8103f8a589"),
	Production("ad301d62-2e3e-451d-8964-ef228f6c4fff");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Environment(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
