// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricName
{
	dataFetchDurationMs("a2ff8e08-cd4f-4652-8699-56637fcdbc1c"),
	recordsFetchedCount("27526e80-4cec-46b7-9c50-ba7f9c596fa6"),
	lastDataFetch("fa8dc91e-3bed-4967-8587-b506913746d3");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricName(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
