// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Service
{
	Use_Host_Setting("25ac8b85-b565-4c01-bf87-ab78f574a404"),
	Username_Password("22a23372-87e9-40bd-8fe8-26b09cf7bc5e"),
	Subscription_Key("170a460e-0664-43ea-a53e-65b3563c5855"),
	Open("44b63a74-d02e-4f10-a342-6220bce73ae0");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Service(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
