// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Service
{
	Use_Host_Setting("af5896a9-6aa2-43fc-8e16-ec05ad9d4937"),
	Username_Password("16eacaf5-832b-471f-884a-a957fa98128b"),
	Subscription_Key("4d346a2b-d1a2-4956-bcf4-a187ab018927"),
	Open("4c0164fa-906d-4715-a138-0d32bdbc649c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Service(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
