// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricName
{
	dataFetchDurationMs("78d307af-c1ea-4cac-bb6e-56f680cc986a"),
	recordsFetchedCount("598177b8-79c7-4a94-8961-9fe702e9b68f"),
	lastDataFetch("08143557-f4ef-44b9-bde5-f7086e5a2eb8");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricName(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
