// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_HTTPMethod
{
	POST("8a42c704-d7e4-4b29-965b-beb085877cd5"),
	PATCH("00d85272-6949-4801-801a-0e88ef94a898"),
	GET("7eda6d91-ee9c-45cf-a056-293ab2d064c4"),
	HEAD("b7250345-7e3c-4040-ad97-ec1a52f74ca2"),
	OPTIONS("8a207b21-bfdb-4bcd-815c-e44cd7dbf039"),
	PUT("ca576d13-bcc4-4a31-9a37-6d959a3985c1"),
	DELETE("349f1006-2176-4514-8bf1-bad63c45d0fa");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_HTTPMethod(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
