// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_HTTPMethod
{
	POST("4e7cd98d-42ed-40b7-83da-52a712b8594a"),
	PATCH("f4a63506-ca66-402d-9afe-f1da034f3891"),
	GET("f0cf77e7-2e64-414b-a423-75d073d35ce6"),
	HEAD("542287d6-6b49-48be-ab41-e658287652b8"),
	OPTIONS("f21ab61c-e47a-4f3d-9f62-fe8782000285"),
	PUT("1d6376da-dc3c-4528-bf95-1117e8eac555"),
	DELETE("5616ede4-07db-4c85-ac2c-14df8524995d");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_HTTPMethod(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
