// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricStatus
{
	Success("521665c2-24dc-4f7a-94c0-e6017ba4c9df"),
	Error("17e737bc-01f9-4c39-b5a6-f6275054a3f5");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
