// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricSyncType
{
	Full("66817e58-3e4e-4ee6-a004-159f26ab2af7"),
	Delta("b3d75075-9916-425b-bb67-a07dc159697f");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricSyncType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
