// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Service
{
	Use_Host_Setting("81f6df5d-f97c-4029-8978-b4d594e265b8"),
	Username_Password("7c5d0d1e-eebb-41fa-a172-5b91bd6afff6"),
	Subscription_Key("0efdc003-772a-4a42-afa4-2e39cea7685c"),
	Open("b2b4b616-bfe7-44a6-a4e5-f251e52b8e91");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Service(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
