// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Environment
{
	Development("5f9de3c2-b7b8-48cd-b0a1-413b773f0aa4"),
	Test("f43bb9a2-7eff-4455-83c0-e404586ae22d"),
	Acceptance("866cfe39-e173-463d-8897-8f8d81a7982b"),
	Production("f8e71d9c-0dd4-42e1-bdca-345517961cc5");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Environment(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
