// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Host
{
	Username_Password("183bb2d5-694a-46b5-bfea-45bf61a607ee"),
	Subscription_Key("7284eae5-8074-4768-acab-a868bbf37779"),
	User_Service_Settings("901d2cba-03d8-4e70-8c68-6fcc5f389f71"),
	OAuth("a5e92c8c-3ee7-44ed-9c12-54f9637029bb"),
	Open("9cd0ead0-3961-4a7d-ad06-06e6dc05abc1");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Host(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
