// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_ServiceType
{
	Rest("69ff6bc5-209b-4b78-a5ac-664e44a44e76"),
	Soap("faa50ffb-97d2-42f4-af04-3728ae85c948"),
	OData("de4e146f-3646-41ea-8745-f2345b2fe545");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ServiceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
