// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricPropertyKey
{
	otherSystem("f0bbc1a6-db32-44e5-9698-e8150384451d"),
	interfaceName("750286e7-118e-48b2-ad70-2f650ab02748"),
	syncType("8b35e8ec-7771-4871-8c14-4f2e9bfe4d64"),
	functionName("37817f32-f564-469a-89e6-47f7d47d2342"),
	status("3268caae-e23b-48db-a263-fde5640bc761"),
	environment("9a31ac51-ee07-442b-a165-9bb0347012e8"),
	appName("79c76522-edd2-4644-bab0-2f31f19e990c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricPropertyKey(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
