// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricPropertyKey
{
	otherSystem("c54d01ab-be74-46e0-b0d4-30677df8c28a"),
	interfaceName("7bfb6441-6047-4c74-83f9-7ec2ebfbd40e"),
	syncType("d0547cc8-5820-42e6-8967-cb8cff8740cc"),
	functionName("e94d3eb8-61d3-4df0-86bd-edceb7a41d61"),
	status("0bb53093-2022-4f6e-94f9-21280bfb7bee"),
	environment("3b2cc18f-4425-4d07-be95-6810dcf7faa3"),
	applicationName("c15cfd9d-77fd-434c-8f48-23cfba0f2c2d");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricPropertyKey(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
