// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Environment
{
	Development("3d88cc19-613a-4aa7-9d7e-8f517851cd7e"),
	Test("cfd30b4b-b995-4211-9c96-edf21ad6f69b"),
	Acceptance("8f56ac28-a034-4202-b4bd-70bc160603b2"),
	Production("97c3ddec-a5d6-4dc6-8d9b-b19c86ef272e");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Environment(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
