// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_HTTPMethod
{
	POST("6347593d-649d-4c28-abec-2613b3f6ed20"),
	PATCH("cfa45940-379b-49f0-9c36-c3717fea2d4b"),
	GET("b5e7edb7-2e9c-49ba-bb4c-668469e25025"),
	HEAD("339030bc-4a18-42e7-a122-d7b980cb90f4"),
	OPTIONS("c10c35ac-e9e2-48f1-b696-d0b751dd11f9"),
	PUT("78b2882d-4814-4a9f-a0d5-256e786329b7"),
	DELETE("86a70b36-e792-4676-b674-ba301a72b622");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_HTTPMethod(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
