// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_MetricName
{
	dataFetchDurationMs("08f0ce76-0b0e-4787-83db-026f99fca369"),
	recordsFetchedCount("565969b8-f543-489f-8313-de7d2cff8b09"),
	lastDataFetch("5ab00f7a-52d8-402c-84ca-0b779f6a2e6b");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_MetricName(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
