// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public enum ENUM_Authentication_Host
{
	Username_Password("e087e44d-4cf9-4115-b466-85a6028fc0f7"),
	Subscription_Key("14ca56b6-6c71-44ee-b735-138d9bf2d85d"),
	User_Service_Settings("d1930784-497a-4e53-935b-9176220c0773"),
	OAuth("1fd604f2-7a6e-45dd-906a-fa2c276a629f"),
	Open("840b5dcb-b27f-4fd3-8db4-c03b8fdf1260");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_Authentication_Host(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
