// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

/**
 * Description of serveal environments, Development, Acceptance, Test, Production
 */
public class Environment implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject environmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.Environment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Environment("Environment"),
		DefaultLogRetentionDaysSuccess("DefaultLogRetentionDaysSuccess"),
		DefaultLogRetentionDaysError("DefaultLogRetentionDaysError");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Environment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Environment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject environmentMendixObject)
	{
		if (environmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!environmentMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.environmentMendixObject = environmentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.Environment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.Environment(context, mendixObject);
	}

	public static aiden_interfaces.proxies.Environment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.Environment.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.Environment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.Environment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of Environment
	 * @param environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Environment.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(aiden_interfaces.proxies.ENUM_Environment environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Environment environment)
	{
		if (environment != null) {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), environment.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), null);
		}
	}

	/**
	 * @return value of DefaultLogRetentionDaysSuccess
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysSuccess()
	{
		return getDefaultLogRetentionDaysSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultLogRetentionDaysSuccess
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DefaultLogRetentionDaysSuccess.toString());
	}

	/**
	 * Set value of DefaultLogRetentionDaysSuccess
	 * @param defaultlogretentiondayssuccess
	 */
	public final void setDefaultLogRetentionDaysSuccess(java.lang.Integer defaultlogretentiondayssuccess)
	{
		setDefaultLogRetentionDaysSuccess(getContext(), defaultlogretentiondayssuccess);
	}

	/**
	 * Set value of DefaultLogRetentionDaysSuccess
	 * @param context
	 * @param defaultlogretentiondayssuccess
	 */
	public final void setDefaultLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer defaultlogretentiondayssuccess)
	{
		getMendixObject().setValue(context, MemberNames.DefaultLogRetentionDaysSuccess.toString(), defaultlogretentiondayssuccess);
	}

	/**
	 * @return value of DefaultLogRetentionDaysError
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysError()
	{
		return getDefaultLogRetentionDaysError(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultLogRetentionDaysError
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DefaultLogRetentionDaysError.toString());
	}

	/**
	 * Set value of DefaultLogRetentionDaysError
	 * @param defaultlogretentiondayserror
	 */
	public final void setDefaultLogRetentionDaysError(java.lang.Integer defaultlogretentiondayserror)
	{
		setDefaultLogRetentionDaysError(getContext(), defaultlogretentiondayserror);
	}

	/**
	 * Set value of DefaultLogRetentionDaysError
	 * @param context
	 * @param defaultlogretentiondayserror
	 */
	public final void setDefaultLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer defaultlogretentiondayserror)
	{
		getMendixObject().setValue(context, MemberNames.DefaultLogRetentionDaysError.toString(), defaultlogretentiondayserror);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return environmentMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.Environment that = (aiden_interfaces.proxies.Environment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
