// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class Host implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject hostMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.Host";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		ServiceType("ServiceType"),
		HostName("HostName"),
		Port("Port"),
		DefaultLogRetentionDaysSuccess("DefaultLogRetentionDaysSuccess"),
		DefaultLogRetentionDaysError("DefaultLogRetentionDaysError"),
		Authentication("Authentication"),
		UserName("UserName"),
		Password("Password"),
		SubscriptionKey("SubscriptionKey"),
		Usage("Usage"),
		OAuthUrl("OAuthUrl"),
		OAuthClientID("OAuthClientID"),
		OAuthClientSecret("OAuthClientSecret"),
		Host_Environment("Aiden_Interfaces.Host_Environment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Host(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Host(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject hostMendixObject)
	{
		if (hostMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!hostMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.hostMendixObject = hostMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.Host initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.Host(context, mendixObject);
	}

	public static aiden_interfaces.proxies.Host load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.Host.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.Host> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.Host.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Get value of ServiceType
	 * @param servicetype
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType()
	{
		return getServiceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceType
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ServiceType.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_ServiceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ServiceType
	 * @param servicetype
	 */
	public final void setServiceType(aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		setServiceType(getContext(), servicetype);
	}

	/**
	 * Set value of ServiceType
	 * @param context
	 * @param servicetype
	 */
	public final void setServiceType(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		if (servicetype != null) {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), servicetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), null);
		}
	}

	/**
	 * @return value of HostName
	 */
	public final java.lang.String getHostName()
	{
		return getHostName(getContext());
	}

	/**
	 * @param context
	 * @return value of HostName
	 */
	public final java.lang.String getHostName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HostName.toString());
	}

	/**
	 * Set value of HostName
	 * @param hostname
	 */
	public final void setHostName(java.lang.String hostname)
	{
		setHostName(getContext(), hostname);
	}

	/**
	 * Set value of HostName
	 * @param context
	 * @param hostname
	 */
	public final void setHostName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hostname)
	{
		getMendixObject().setValue(context, MemberNames.HostName.toString(), hostname);
	}

	/**
	 * @return value of Port
	 */
	public final java.lang.String getPort()
	{
		return getPort(getContext());
	}

	/**
	 * @param context
	 * @return value of Port
	 */
	public final java.lang.String getPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Port.toString());
	}

	/**
	 * Set value of Port
	 * @param port
	 */
	public final void setPort(java.lang.String port)
	{
		setPort(getContext(), port);
	}

	/**
	 * Set value of Port
	 * @param context
	 * @param port
	 */
	public final void setPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String port)
	{
		getMendixObject().setValue(context, MemberNames.Port.toString(), port);
	}

	/**
	 * @return value of DefaultLogRetentionDaysSuccess
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysSuccess()
	{
		return getDefaultLogRetentionDaysSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultLogRetentionDaysSuccess
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DefaultLogRetentionDaysSuccess.toString());
	}

	/**
	 * Set value of DefaultLogRetentionDaysSuccess
	 * @param defaultlogretentiondayssuccess
	 */
	public final void setDefaultLogRetentionDaysSuccess(java.lang.Integer defaultlogretentiondayssuccess)
	{
		setDefaultLogRetentionDaysSuccess(getContext(), defaultlogretentiondayssuccess);
	}

	/**
	 * Set value of DefaultLogRetentionDaysSuccess
	 * @param context
	 * @param defaultlogretentiondayssuccess
	 */
	public final void setDefaultLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer defaultlogretentiondayssuccess)
	{
		getMendixObject().setValue(context, MemberNames.DefaultLogRetentionDaysSuccess.toString(), defaultlogretentiondayssuccess);
	}

	/**
	 * @return value of DefaultLogRetentionDaysError
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysError()
	{
		return getDefaultLogRetentionDaysError(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultLogRetentionDaysError
	 */
	public final java.lang.Integer getDefaultLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DefaultLogRetentionDaysError.toString());
	}

	/**
	 * Set value of DefaultLogRetentionDaysError
	 * @param defaultlogretentiondayserror
	 */
	public final void setDefaultLogRetentionDaysError(java.lang.Integer defaultlogretentiondayserror)
	{
		setDefaultLogRetentionDaysError(getContext(), defaultlogretentiondayserror);
	}

	/**
	 * Set value of DefaultLogRetentionDaysError
	 * @param context
	 * @param defaultlogretentiondayserror
	 */
	public final void setDefaultLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer defaultlogretentiondayserror)
	{
		getMendixObject().setValue(context, MemberNames.DefaultLogRetentionDaysError.toString(), defaultlogretentiondayserror);
	}

	/**
	 * Get value of Authentication
	 * @param authentication
	 */
	public final aiden_interfaces.proxies.ENUM_Authentication_Host getAuthentication()
	{
		return getAuthentication(getContext());
	}

	/**
	 * @param context
	 * @return value of Authentication
	 */
	public final aiden_interfaces.proxies.ENUM_Authentication_Host getAuthentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Authentication.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Authentication_Host.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Authentication
	 * @param authentication
	 */
	public final void setAuthentication(aiden_interfaces.proxies.ENUM_Authentication_Host authentication)
	{
		setAuthentication(getContext(), authentication);
	}

	/**
	 * Set value of Authentication
	 * @param context
	 * @param authentication
	 */
	public final void setAuthentication(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Authentication_Host authentication)
	{
		if (authentication != null) {
			getMendixObject().setValue(context, MemberNames.Authentication.toString(), authentication.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Authentication.toString(), null);
		}
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of SubscriptionKey
	 */
	public final java.lang.String getSubscriptionKey()
	{
		return getSubscriptionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionKey
	 */
	public final java.lang.String getSubscriptionKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionKey.toString());
	}

	/**
	 * Set value of SubscriptionKey
	 * @param subscriptionkey
	 */
	public final void setSubscriptionKey(java.lang.String subscriptionkey)
	{
		setSubscriptionKey(getContext(), subscriptionkey);
	}

	/**
	 * Set value of SubscriptionKey
	 * @param context
	 * @param subscriptionkey
	 */
	public final void setSubscriptionKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionkey)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionKey.toString(), subscriptionkey);
	}

	/**
	 * @return value of Usage
	 */
	public final java.lang.Integer getUsage()
	{
		return getUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of Usage
	 */
	public final java.lang.Integer getUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Usage.toString());
	}

	/**
	 * Set value of Usage
	 * @param usage
	 */
	public final void setUsage(java.lang.Integer usage)
	{
		setUsage(getContext(), usage);
	}

	/**
	 * Set value of Usage
	 * @param context
	 * @param usage
	 */
	public final void setUsage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer usage)
	{
		getMendixObject().setValue(context, MemberNames.Usage.toString(), usage);
	}

	/**
	 * @return value of OAuthUrl
	 */
	public final java.lang.String getOAuthUrl()
	{
		return getOAuthUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthUrl
	 */
	public final java.lang.String getOAuthUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OAuthUrl.toString());
	}

	/**
	 * Set value of OAuthUrl
	 * @param oauthurl
	 */
	public final void setOAuthUrl(java.lang.String oauthurl)
	{
		setOAuthUrl(getContext(), oauthurl);
	}

	/**
	 * Set value of OAuthUrl
	 * @param context
	 * @param oauthurl
	 */
	public final void setOAuthUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oauthurl)
	{
		getMendixObject().setValue(context, MemberNames.OAuthUrl.toString(), oauthurl);
	}

	/**
	 * @return value of OAuthClientID
	 */
	public final java.lang.String getOAuthClientID()
	{
		return getOAuthClientID(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthClientID
	 */
	public final java.lang.String getOAuthClientID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OAuthClientID.toString());
	}

	/**
	 * Set value of OAuthClientID
	 * @param oauthclientid
	 */
	public final void setOAuthClientID(java.lang.String oauthclientid)
	{
		setOAuthClientID(getContext(), oauthclientid);
	}

	/**
	 * Set value of OAuthClientID
	 * @param context
	 * @param oauthclientid
	 */
	public final void setOAuthClientID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oauthclientid)
	{
		getMendixObject().setValue(context, MemberNames.OAuthClientID.toString(), oauthclientid);
	}

	/**
	 * @return value of OAuthClientSecret
	 */
	public final java.lang.String getOAuthClientSecret()
	{
		return getOAuthClientSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthClientSecret
	 */
	public final java.lang.String getOAuthClientSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OAuthClientSecret.toString());
	}

	/**
	 * Set value of OAuthClientSecret
	 * @param oauthclientsecret
	 */
	public final void setOAuthClientSecret(java.lang.String oauthclientsecret)
	{
		setOAuthClientSecret(getContext(), oauthclientsecret);
	}

	/**
	 * Set value of OAuthClientSecret
	 * @param context
	 * @param oauthclientsecret
	 */
	public final void setOAuthClientSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oauthclientsecret)
	{
		getMendixObject().setValue(context, MemberNames.OAuthClientSecret.toString(), oauthclientsecret);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Host_Environment
	 */
	public final aiden_interfaces.proxies.Environment getHost_Environment() throws com.mendix.core.CoreException
	{
		return getHost_Environment(getContext());
	}

	/**
	 * @param context
	 * @return value of Host_Environment
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Environment getHost_Environment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Environment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Host_Environment.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Environment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Host_Environment
	 * @param host_environment
	 */
	public final void setHost_Environment(aiden_interfaces.proxies.Environment host_environment)
	{
		setHost_Environment(getContext(), host_environment);
	}

	/**
	 * Set value of Host_Environment
	 * @param context
	 * @param host_environment
	 */
	public final void setHost_Environment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Environment host_environment)
	{
		if (host_environment == null) {
			getMendixObject().setValue(context, MemberNames.Host_Environment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Host_Environment.toString(), host_environment.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return hostMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.Host that = (aiden_interfaces.proxies.Host) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
