// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class Mapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.Mapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Mapping_ConnectTo("Aiden_Interfaces.Mapping_ConnectTo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Mapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Mapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mappingMendixObject)
	{
		if (mappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!mappingMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mappingMendixObject = mappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.Mapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.Mapping(context, mendixObject);
	}

	public static aiden_interfaces.proxies.Mapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.Mapping.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.Mapping> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.Mapping.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Mapping_ConnectTo
	 */
	public final aiden_interfaces.proxies.Environment getMapping_ConnectTo() throws com.mendix.core.CoreException
	{
		return getMapping_ConnectTo(getContext());
	}

	/**
	 * @param context
	 * @return value of Mapping_ConnectTo
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Environment getMapping_ConnectTo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Environment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Mapping_ConnectTo.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Environment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Mapping_ConnectTo
	 * @param mapping_connectto
	 */
	public final void setMapping_ConnectTo(aiden_interfaces.proxies.Environment mapping_connectto)
	{
		setMapping_ConnectTo(getContext(), mapping_connectto);
	}

	/**
	 * Set value of Mapping_ConnectTo
	 * @param context
	 * @param mapping_connectto
	 */
	public final void setMapping_ConnectTo(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Environment mapping_connectto)
	{
		if (mapping_connectto == null) {
			getMendixObject().setValue(context, MemberNames.Mapping_ConnectTo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Mapping_ConnectTo.toString(), mapping_connectto.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mappingMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.Mapping that = (aiden_interfaces.proxies.Mapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
