// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class QueryHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject queryHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.QueryHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Query("Query"),
		FilterUsed("FilterUsed"),
		AuthorizationString("AuthorizationString"),
		BaseUrl("BaseUrl"),
		HostName("HostName"),
		CSRFToken("CSRFToken"),
		Cookie("Cookie"),
		StartedAt("StartedAt"),
		ExpiresAt("ExpiresAt"),
		MaterialNumber("MaterialNumber"),
		ConditionRecord("ConditionRecord"),
		ETag("ETag"),
		JSON("JSON"),
		SelectUsed("SelectUsed"),
		Environment("Environment"),
		QueryHelper_Environment("Aiden_Interfaces.QueryHelper_Environment"),
		QueryHelper_Host("Aiden_Interfaces.QueryHelper_Host"),
		QueryHelper_Service("Aiden_Interfaces.QueryHelper_Service"),
		QueryHelper_Token("Aiden_Interfaces.QueryHelper_Token");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public QueryHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected QueryHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject queryHelperMendixObject)
	{
		if (queryHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!queryHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.queryHelperMendixObject = queryHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.QueryHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.QueryHelper(context, mendixObject);
	}

	public static aiden_interfaces.proxies.QueryHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.QueryHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of FilterUsed
	 */
	public final java.lang.Boolean getFilterUsed()
	{
		return getFilterUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of FilterUsed
	 */
	public final java.lang.Boolean getFilterUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FilterUsed.toString());
	}

	/**
	 * Set value of FilterUsed
	 * @param filterused
	 */
	public final void setFilterUsed(java.lang.Boolean filterused)
	{
		setFilterUsed(getContext(), filterused);
	}

	/**
	 * Set value of FilterUsed
	 * @param context
	 * @param filterused
	 */
	public final void setFilterUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean filterused)
	{
		getMendixObject().setValue(context, MemberNames.FilterUsed.toString(), filterused);
	}

	/**
	 * @return value of AuthorizationString
	 */
	public final java.lang.String getAuthorizationString()
	{
		return getAuthorizationString(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationString
	 */
	public final java.lang.String getAuthorizationString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthorizationString.toString());
	}

	/**
	 * Set value of AuthorizationString
	 * @param authorizationstring
	 */
	public final void setAuthorizationString(java.lang.String authorizationstring)
	{
		setAuthorizationString(getContext(), authorizationstring);
	}

	/**
	 * Set value of AuthorizationString
	 * @param context
	 * @param authorizationstring
	 */
	public final void setAuthorizationString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorizationstring)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationString.toString(), authorizationstring);
	}

	/**
	 * @return value of BaseUrl
	 */
	public final java.lang.String getBaseUrl()
	{
		return getBaseUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseUrl
	 */
	public final java.lang.String getBaseUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BaseUrl.toString());
	}

	/**
	 * Set value of BaseUrl
	 * @param baseurl
	 */
	public final void setBaseUrl(java.lang.String baseurl)
	{
		setBaseUrl(getContext(), baseurl);
	}

	/**
	 * Set value of BaseUrl
	 * @param context
	 * @param baseurl
	 */
	public final void setBaseUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String baseurl)
	{
		getMendixObject().setValue(context, MemberNames.BaseUrl.toString(), baseurl);
	}

	/**
	 * @return value of HostName
	 */
	public final java.lang.String getHostName()
	{
		return getHostName(getContext());
	}

	/**
	 * @param context
	 * @return value of HostName
	 */
	public final java.lang.String getHostName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HostName.toString());
	}

	/**
	 * Set value of HostName
	 * @param hostname
	 */
	public final void setHostName(java.lang.String hostname)
	{
		setHostName(getContext(), hostname);
	}

	/**
	 * Set value of HostName
	 * @param context
	 * @param hostname
	 */
	public final void setHostName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hostname)
	{
		getMendixObject().setValue(context, MemberNames.HostName.toString(), hostname);
	}

	/**
	 * @return value of CSRFToken
	 */
	public final java.lang.String getCSRFToken()
	{
		return getCSRFToken(getContext());
	}

	/**
	 * @param context
	 * @return value of CSRFToken
	 */
	public final java.lang.String getCSRFToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CSRFToken.toString());
	}

	/**
	 * Set value of CSRFToken
	 * @param csrftoken
	 */
	public final void setCSRFToken(java.lang.String csrftoken)
	{
		setCSRFToken(getContext(), csrftoken);
	}

	/**
	 * Set value of CSRFToken
	 * @param context
	 * @param csrftoken
	 */
	public final void setCSRFToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csrftoken)
	{
		getMendixObject().setValue(context, MemberNames.CSRFToken.toString(), csrftoken);
	}

	/**
	 * @return value of Cookie
	 */
	public final java.lang.String getCookie()
	{
		return getCookie(getContext());
	}

	/**
	 * @param context
	 * @return value of Cookie
	 */
	public final java.lang.String getCookie(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cookie.toString());
	}

	/**
	 * Set value of Cookie
	 * @param cookie
	 */
	public final void setCookie(java.lang.String cookie)
	{
		setCookie(getContext(), cookie);
	}

	/**
	 * Set value of Cookie
	 * @param context
	 * @param cookie
	 */
	public final void setCookie(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cookie)
	{
		getMendixObject().setValue(context, MemberNames.Cookie.toString(), cookie);
	}

	/**
	 * @return value of StartedAt
	 */
	public final java.util.Date getStartedAt()
	{
		return getStartedAt(getContext());
	}

	/**
	 * @param context
	 * @return value of StartedAt
	 */
	public final java.util.Date getStartedAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartedAt.toString());
	}

	/**
	 * Set value of StartedAt
	 * @param startedat
	 */
	public final void setStartedAt(java.util.Date startedat)
	{
		setStartedAt(getContext(), startedat);
	}

	/**
	 * Set value of StartedAt
	 * @param context
	 * @param startedat
	 */
	public final void setStartedAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startedat)
	{
		getMendixObject().setValue(context, MemberNames.StartedAt.toString(), startedat);
	}

	/**
	 * @return value of ExpiresAt
	 */
	public final java.util.Date getExpiresAt()
	{
		return getExpiresAt(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiresAt
	 */
	public final java.util.Date getExpiresAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpiresAt.toString());
	}

	/**
	 * Set value of ExpiresAt
	 * @param expiresat
	 */
	public final void setExpiresAt(java.util.Date expiresat)
	{
		setExpiresAt(getContext(), expiresat);
	}

	/**
	 * Set value of ExpiresAt
	 * @param context
	 * @param expiresat
	 */
	public final void setExpiresAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expiresat)
	{
		getMendixObject().setValue(context, MemberNames.ExpiresAt.toString(), expiresat);
	}

	/**
	 * @return value of MaterialNumber
	 */
	public final java.lang.String getMaterialNumber()
	{
		return getMaterialNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialNumber
	 */
	public final java.lang.String getMaterialNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialNumber.toString());
	}

	/**
	 * Set value of MaterialNumber
	 * @param materialnumber
	 */
	public final void setMaterialNumber(java.lang.String materialnumber)
	{
		setMaterialNumber(getContext(), materialnumber);
	}

	/**
	 * Set value of MaterialNumber
	 * @param context
	 * @param materialnumber
	 */
	public final void setMaterialNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialnumber)
	{
		getMendixObject().setValue(context, MemberNames.MaterialNumber.toString(), materialnumber);
	}

	/**
	 * @return value of ConditionRecord
	 */
	public final java.lang.String getConditionRecord()
	{
		return getConditionRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of ConditionRecord
	 */
	public final java.lang.String getConditionRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ConditionRecord.toString());
	}

	/**
	 * Set value of ConditionRecord
	 * @param conditionrecord
	 */
	public final void setConditionRecord(java.lang.String conditionrecord)
	{
		setConditionRecord(getContext(), conditionrecord);
	}

	/**
	 * Set value of ConditionRecord
	 * @param context
	 * @param conditionrecord
	 */
	public final void setConditionRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String conditionrecord)
	{
		getMendixObject().setValue(context, MemberNames.ConditionRecord.toString(), conditionrecord);
	}

	/**
	 * @return value of ETag
	 */
	public final java.lang.String getETag()
	{
		return getETag(getContext());
	}

	/**
	 * @param context
	 * @return value of ETag
	 */
	public final java.lang.String getETag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ETag.toString());
	}

	/**
	 * Set value of ETag
	 * @param etag
	 */
	public final void setETag(java.lang.String etag)
	{
		setETag(getContext(), etag);
	}

	/**
	 * Set value of ETag
	 * @param context
	 * @param etag
	 */
	public final void setETag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String etag)
	{
		getMendixObject().setValue(context, MemberNames.ETag.toString(), etag);
	}

	/**
	 * @return value of JSON
	 */
	public final java.lang.String getJSON()
	{
		return getJSON(getContext());
	}

	/**
	 * @param context
	 * @return value of JSON
	 */
	public final java.lang.String getJSON(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JSON.toString());
	}

	/**
	 * Set value of JSON
	 * @param json
	 */
	public final void setJSON(java.lang.String json)
	{
		setJSON(getContext(), json);
	}

	/**
	 * Set value of JSON
	 * @param context
	 * @param json
	 */
	public final void setJSON(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String json)
	{
		getMendixObject().setValue(context, MemberNames.JSON.toString(), json);
	}

	/**
	 * @return value of SelectUsed
	 */
	public final java.lang.Boolean getSelectUsed()
	{
		return getSelectUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectUsed
	 */
	public final java.lang.Boolean getSelectUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectUsed.toString());
	}

	/**
	 * Set value of SelectUsed
	 * @param selectused
	 */
	public final void setSelectUsed(java.lang.Boolean selectused)
	{
		setSelectUsed(getContext(), selectused);
	}

	/**
	 * Set value of SelectUsed
	 * @param context
	 * @param selectused
	 */
	public final void setSelectUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectused)
	{
		getMendixObject().setValue(context, MemberNames.SelectUsed.toString(), selectused);
	}

	/**
	 * Get value of Environment
	 * @param environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Environment.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(aiden_interfaces.proxies.ENUM_Environment environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Environment environment)
	{
		if (environment != null) {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), environment.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of QueryHelper_Environment
	 */
	public final aiden_interfaces.proxies.Environment getQueryHelper_Environment() throws com.mendix.core.CoreException
	{
		return getQueryHelper_Environment(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryHelper_Environment
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Environment getQueryHelper_Environment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Environment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueryHelper_Environment.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Environment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of QueryHelper_Environment
	 * @param queryhelper_environment
	 */
	public final void setQueryHelper_Environment(aiden_interfaces.proxies.Environment queryhelper_environment)
	{
		setQueryHelper_Environment(getContext(), queryhelper_environment);
	}

	/**
	 * Set value of QueryHelper_Environment
	 * @param context
	 * @param queryhelper_environment
	 */
	public final void setQueryHelper_Environment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Environment queryhelper_environment)
	{
		if (queryhelper_environment == null) {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Environment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Environment.toString(), queryhelper_environment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of QueryHelper_Host
	 */
	public final aiden_interfaces.proxies.Host getQueryHelper_Host() throws com.mendix.core.CoreException
	{
		return getQueryHelper_Host(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryHelper_Host
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Host getQueryHelper_Host(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Host result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueryHelper_Host.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Host.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of QueryHelper_Host
	 * @param queryhelper_host
	 */
	public final void setQueryHelper_Host(aiden_interfaces.proxies.Host queryhelper_host)
	{
		setQueryHelper_Host(getContext(), queryhelper_host);
	}

	/**
	 * Set value of QueryHelper_Host
	 * @param context
	 * @param queryhelper_host
	 */
	public final void setQueryHelper_Host(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Host queryhelper_host)
	{
		if (queryhelper_host == null) {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Host.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Host.toString(), queryhelper_host.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of QueryHelper_Service
	 */
	public final aiden_interfaces.proxies.Service getQueryHelper_Service() throws com.mendix.core.CoreException
	{
		return getQueryHelper_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryHelper_Service
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Service getQueryHelper_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueryHelper_Service.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Service.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of QueryHelper_Service
	 * @param queryhelper_service
	 */
	public final void setQueryHelper_Service(aiden_interfaces.proxies.Service queryhelper_service)
	{
		setQueryHelper_Service(getContext(), queryhelper_service);
	}

	/**
	 * Set value of QueryHelper_Service
	 * @param context
	 * @param queryhelper_service
	 */
	public final void setQueryHelper_Service(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Service queryhelper_service)
	{
		if (queryhelper_service == null) {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Service.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Service.toString(), queryhelper_service.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of QueryHelper_Token
	 */
	public final aiden_interfaces.proxies.Token getQueryHelper_Token() throws com.mendix.core.CoreException
	{
		return getQueryHelper_Token(getContext());
	}

	/**
	 * @param context
	 * @return value of QueryHelper_Token
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Token getQueryHelper_Token(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Token result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.QueryHelper_Token.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Token.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of QueryHelper_Token
	 * @param queryhelper_token
	 */
	public final void setQueryHelper_Token(aiden_interfaces.proxies.Token queryhelper_token)
	{
		setQueryHelper_Token(getContext(), queryhelper_token);
	}

	/**
	 * Set value of QueryHelper_Token
	 * @param context
	 * @param queryhelper_token
	 */
	public final void setQueryHelper_Token(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Token queryhelper_token)
	{
		if (queryhelper_token == null) {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Token.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.QueryHelper_Token.toString(), queryhelper_token.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return queryHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.QueryHelper that = (aiden_interfaces.proxies.QueryHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
