// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class Service implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serviceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.Service";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceType("ServiceType"),
		EndPoint("EndPoint"),
		Methode("Methode"),
		Authentication("Authentication"),
		SubscriptionKey("SubscriptionKey"),
		UserName("UserName"),
		Password("Password"),
		Key("Key"),
		Description("Description"),
		LogRetentionDaysSuccess("LogRetentionDaysSuccess"),
		LogRetentionDaysError("LogRetentionDaysError"),
		Service_Host("Aiden_Interfaces.Service_Host");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Service(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Service(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceMendixObject)
	{
		if (serviceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!serviceMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.serviceMendixObject = serviceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.Service(context, mendixObject);
	}

	public static aiden_interfaces.proxies.Service load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.Service.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.Service> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.Service.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of ServiceType
	 * @param servicetype
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType()
	{
		return getServiceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceType
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ServiceType.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_ServiceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ServiceType
	 * @param servicetype
	 */
	public final void setServiceType(aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		setServiceType(getContext(), servicetype);
	}

	/**
	 * Set value of ServiceType
	 * @param context
	 * @param servicetype
	 */
	public final void setServiceType(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		if (servicetype != null) {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), servicetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), null);
		}
	}

	/**
	 * @return value of EndPoint
	 */
	public final java.lang.String getEndPoint()
	{
		return getEndPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of EndPoint
	 */
	public final java.lang.String getEndPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndPoint.toString());
	}

	/**
	 * Set value of EndPoint
	 * @param endpoint
	 */
	public final void setEndPoint(java.lang.String endpoint)
	{
		setEndPoint(getContext(), endpoint);
	}

	/**
	 * Set value of EndPoint
	 * @param context
	 * @param endpoint
	 */
	public final void setEndPoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpoint)
	{
		getMendixObject().setValue(context, MemberNames.EndPoint.toString(), endpoint);
	}

	/**
	 * @return value of Methode
	 */
	public final java.lang.String getMethode()
	{
		return getMethode(getContext());
	}

	/**
	 * @param context
	 * @return value of Methode
	 */
	public final java.lang.String getMethode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Methode.toString());
	}

	/**
	 * Set value of Methode
	 * @param methode
	 */
	public final void setMethode(java.lang.String methode)
	{
		setMethode(getContext(), methode);
	}

	/**
	 * Set value of Methode
	 * @param context
	 * @param methode
	 */
	public final void setMethode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String methode)
	{
		getMendixObject().setValue(context, MemberNames.Methode.toString(), methode);
	}

	/**
	 * Get value of Authentication
	 * @param authentication
	 */
	public final aiden_interfaces.proxies.ENUM_Authentication_Service getAuthentication()
	{
		return getAuthentication(getContext());
	}

	/**
	 * @param context
	 * @return value of Authentication
	 */
	public final aiden_interfaces.proxies.ENUM_Authentication_Service getAuthentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Authentication.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Authentication_Service.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Authentication
	 * @param authentication
	 */
	public final void setAuthentication(aiden_interfaces.proxies.ENUM_Authentication_Service authentication)
	{
		setAuthentication(getContext(), authentication);
	}

	/**
	 * Set value of Authentication
	 * @param context
	 * @param authentication
	 */
	public final void setAuthentication(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Authentication_Service authentication)
	{
		if (authentication != null) {
			getMendixObject().setValue(context, MemberNames.Authentication.toString(), authentication.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Authentication.toString(), null);
		}
	}

	/**
	 * @return value of SubscriptionKey
	 */
	public final java.lang.String getSubscriptionKey()
	{
		return getSubscriptionKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionKey
	 */
	public final java.lang.String getSubscriptionKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionKey.toString());
	}

	/**
	 * Set value of SubscriptionKey
	 * @param subscriptionkey
	 */
	public final void setSubscriptionKey(java.lang.String subscriptionkey)
	{
		setSubscriptionKey(getContext(), subscriptionkey);
	}

	/**
	 * Set value of SubscriptionKey
	 * @param context
	 * @param subscriptionkey
	 */
	public final void setSubscriptionKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionkey)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionKey.toString(), subscriptionkey);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of LogRetentionDaysSuccess
	 */
	public final java.lang.Integer getLogRetentionDaysSuccess()
	{
		return getLogRetentionDaysSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of LogRetentionDaysSuccess
	 */
	public final java.lang.Integer getLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LogRetentionDaysSuccess.toString());
	}

	/**
	 * Set value of LogRetentionDaysSuccess
	 * @param logretentiondayssuccess
	 */
	public final void setLogRetentionDaysSuccess(java.lang.Integer logretentiondayssuccess)
	{
		setLogRetentionDaysSuccess(getContext(), logretentiondayssuccess);
	}

	/**
	 * Set value of LogRetentionDaysSuccess
	 * @param context
	 * @param logretentiondayssuccess
	 */
	public final void setLogRetentionDaysSuccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer logretentiondayssuccess)
	{
		getMendixObject().setValue(context, MemberNames.LogRetentionDaysSuccess.toString(), logretentiondayssuccess);
	}

	/**
	 * @return value of LogRetentionDaysError
	 */
	public final java.lang.Integer getLogRetentionDaysError()
	{
		return getLogRetentionDaysError(getContext());
	}

	/**
	 * @param context
	 * @return value of LogRetentionDaysError
	 */
	public final java.lang.Integer getLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.LogRetentionDaysError.toString());
	}

	/**
	 * Set value of LogRetentionDaysError
	 * @param logretentiondayserror
	 */
	public final void setLogRetentionDaysError(java.lang.Integer logretentiondayserror)
	{
		setLogRetentionDaysError(getContext(), logretentiondayserror);
	}

	/**
	 * Set value of LogRetentionDaysError
	 * @param context
	 * @param logretentiondayserror
	 */
	public final void setLogRetentionDaysError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer logretentiondayserror)
	{
		getMendixObject().setValue(context, MemberNames.LogRetentionDaysError.toString(), logretentiondayserror);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Service_Host
	 */
	public final java.util.List<aiden_interfaces.proxies.Host> getService_Host() throws com.mendix.core.CoreException
	{
		return getService_Host(getContext());
	}

	/**
	 * @param context
	 * @return value of Service_Host
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<aiden_interfaces.proxies.Host> getService_Host(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<aiden_interfaces.proxies.Host> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Service_Host.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(aiden_interfaces.proxies.Host.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Service_Host
	 * @param service_host
	 */
	public final void setService_Host(java.util.List<aiden_interfaces.proxies.Host> service_host)
	{
		setService_Host(getContext(), service_host);
	}

	/**
	 * Set value of Service_Host
	 * @param context
	 * @param service_host
	 */
	public final void setService_Host(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<aiden_interfaces.proxies.Host> service_host)
	{
		var identifiers = service_host
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Service_Host.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serviceMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.Service that = (aiden_interfaces.proxies.Service) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
