// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class TransactionLog implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.TransactionLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		User("User"),
		JSON_Request("JSON_Request"),
		JSON_Response("JSON_Response"),
		Result("Result"),
		latestError_Message("latestError_Message"),
		latestError_Stacktrace("latestError_Stacktrace"),
		latestHttpResponse_Statuscode("latestHttpResponse_Statuscode"),
		latestHttpResponse_ReasonPhrase("latestHttpResponse_ReasonPhrase"),
		BaseURL("BaseURL"),
		EndPoint("EndPoint"),
		Query("Query"),
		Duration("Duration"),
		RecordCount("RecordCount"),
		HTTPMethod("HTTPMethod"),
		TransactionLog_Service("Aiden_Interfaces.TransactionLog_Service"),
		TransactionLog_Transaction("Aiden_Interfaces.TransactionLog_Transaction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransactionLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TransactionLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionLogMendixObject)
	{
		if (transactionLogMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!transactionLogMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionLogMendixObject = transactionLogMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.TransactionLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.TransactionLog(context, mendixObject);
	}

	public static aiden_interfaces.proxies.TransactionLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.TransactionLog.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.TransactionLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.TransactionLog.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of User
	 */
	public final java.lang.String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final java.lang.String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(java.lang.String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of JSON_Request
	 */
	public final java.lang.String getJSON_Request()
	{
		return getJSON_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of JSON_Request
	 */
	public final java.lang.String getJSON_Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JSON_Request.toString());
	}

	/**
	 * Set value of JSON_Request
	 * @param json_request
	 */
	public final void setJSON_Request(java.lang.String json_request)
	{
		setJSON_Request(getContext(), json_request);
	}

	/**
	 * Set value of JSON_Request
	 * @param context
	 * @param json_request
	 */
	public final void setJSON_Request(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String json_request)
	{
		getMendixObject().setValue(context, MemberNames.JSON_Request.toString(), json_request);
	}

	/**
	 * @return value of JSON_Response
	 */
	public final java.lang.String getJSON_Response()
	{
		return getJSON_Response(getContext());
	}

	/**
	 * @param context
	 * @return value of JSON_Response
	 */
	public final java.lang.String getJSON_Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JSON_Response.toString());
	}

	/**
	 * Set value of JSON_Response
	 * @param json_response
	 */
	public final void setJSON_Response(java.lang.String json_response)
	{
		setJSON_Response(getContext(), json_response);
	}

	/**
	 * Set value of JSON_Response
	 * @param context
	 * @param json_response
	 */
	public final void setJSON_Response(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String json_response)
	{
		getMendixObject().setValue(context, MemberNames.JSON_Response.toString(), json_response);
	}

	/**
	 * Get value of Result
	 * @param result
	 */
	public final aiden_interfaces.proxies.ENUM_Result getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final aiden_interfaces.proxies.ENUM_Result getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Result.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Result.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(aiden_interfaces.proxies.ENUM_Result result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Result result)
	{
		if (result != null) {
			getMendixObject().setValue(context, MemberNames.Result.toString(), result.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Result.toString(), null);
		}
	}

	/**
	 * @return value of latestError_Message
	 */
	public final java.lang.String getlatestError_Message()
	{
		return getlatestError_Message(getContext());
	}

	/**
	 * @param context
	 * @return value of latestError_Message
	 */
	public final java.lang.String getlatestError_Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.latestError_Message.toString());
	}

	/**
	 * Set value of latestError_Message
	 * @param latesterror_message
	 */
	public final void setlatestError_Message(java.lang.String latesterror_message)
	{
		setlatestError_Message(getContext(), latesterror_message);
	}

	/**
	 * Set value of latestError_Message
	 * @param context
	 * @param latesterror_message
	 */
	public final void setlatestError_Message(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latesterror_message)
	{
		getMendixObject().setValue(context, MemberNames.latestError_Message.toString(), latesterror_message);
	}

	/**
	 * @return value of latestError_Stacktrace
	 */
	public final java.lang.String getlatestError_Stacktrace()
	{
		return getlatestError_Stacktrace(getContext());
	}

	/**
	 * @param context
	 * @return value of latestError_Stacktrace
	 */
	public final java.lang.String getlatestError_Stacktrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.latestError_Stacktrace.toString());
	}

	/**
	 * Set value of latestError_Stacktrace
	 * @param latesterror_stacktrace
	 */
	public final void setlatestError_Stacktrace(java.lang.String latesterror_stacktrace)
	{
		setlatestError_Stacktrace(getContext(), latesterror_stacktrace);
	}

	/**
	 * Set value of latestError_Stacktrace
	 * @param context
	 * @param latesterror_stacktrace
	 */
	public final void setlatestError_Stacktrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latesterror_stacktrace)
	{
		getMendixObject().setValue(context, MemberNames.latestError_Stacktrace.toString(), latesterror_stacktrace);
	}

	/**
	 * @return value of latestHttpResponse_Statuscode
	 */
	public final java.lang.Integer getlatestHttpResponse_Statuscode()
	{
		return getlatestHttpResponse_Statuscode(getContext());
	}

	/**
	 * @param context
	 * @return value of latestHttpResponse_Statuscode
	 */
	public final java.lang.Integer getlatestHttpResponse_Statuscode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.latestHttpResponse_Statuscode.toString());
	}

	/**
	 * Set value of latestHttpResponse_Statuscode
	 * @param latesthttpresponse_statuscode
	 */
	public final void setlatestHttpResponse_Statuscode(java.lang.Integer latesthttpresponse_statuscode)
	{
		setlatestHttpResponse_Statuscode(getContext(), latesthttpresponse_statuscode);
	}

	/**
	 * Set value of latestHttpResponse_Statuscode
	 * @param context
	 * @param latesthttpresponse_statuscode
	 */
	public final void setlatestHttpResponse_Statuscode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer latesthttpresponse_statuscode)
	{
		getMendixObject().setValue(context, MemberNames.latestHttpResponse_Statuscode.toString(), latesthttpresponse_statuscode);
	}

	/**
	 * @return value of latestHttpResponse_ReasonPhrase
	 */
	public final java.lang.String getlatestHttpResponse_ReasonPhrase()
	{
		return getlatestHttpResponse_ReasonPhrase(getContext());
	}

	/**
	 * @param context
	 * @return value of latestHttpResponse_ReasonPhrase
	 */
	public final java.lang.String getlatestHttpResponse_ReasonPhrase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.latestHttpResponse_ReasonPhrase.toString());
	}

	/**
	 * Set value of latestHttpResponse_ReasonPhrase
	 * @param latesthttpresponse_reasonphrase
	 */
	public final void setlatestHttpResponse_ReasonPhrase(java.lang.String latesthttpresponse_reasonphrase)
	{
		setlatestHttpResponse_ReasonPhrase(getContext(), latesthttpresponse_reasonphrase);
	}

	/**
	 * Set value of latestHttpResponse_ReasonPhrase
	 * @param context
	 * @param latesthttpresponse_reasonphrase
	 */
	public final void setlatestHttpResponse_ReasonPhrase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latesthttpresponse_reasonphrase)
	{
		getMendixObject().setValue(context, MemberNames.latestHttpResponse_ReasonPhrase.toString(), latesthttpresponse_reasonphrase);
	}

	/**
	 * @return value of BaseURL
	 */
	public final java.lang.String getBaseURL()
	{
		return getBaseURL(getContext());
	}

	/**
	 * @param context
	 * @return value of BaseURL
	 */
	public final java.lang.String getBaseURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BaseURL.toString());
	}

	/**
	 * Set value of BaseURL
	 * @param baseurl
	 */
	public final void setBaseURL(java.lang.String baseurl)
	{
		setBaseURL(getContext(), baseurl);
	}

	/**
	 * Set value of BaseURL
	 * @param context
	 * @param baseurl
	 */
	public final void setBaseURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String baseurl)
	{
		getMendixObject().setValue(context, MemberNames.BaseURL.toString(), baseurl);
	}

	/**
	 * @return value of EndPoint
	 */
	public final java.lang.String getEndPoint()
	{
		return getEndPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of EndPoint
	 */
	public final java.lang.String getEndPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EndPoint.toString());
	}

	/**
	 * Set value of EndPoint
	 * @param endpoint
	 */
	public final void setEndPoint(java.lang.String endpoint)
	{
		setEndPoint(getContext(), endpoint);
	}

	/**
	 * Set value of EndPoint
	 * @param context
	 * @param endpoint
	 */
	public final void setEndPoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String endpoint)
	{
		getMendixObject().setValue(context, MemberNames.EndPoint.toString(), endpoint);
	}

	/**
	 * @return value of Query
	 */
	public final java.lang.String getQuery()
	{
		return getQuery(getContext());
	}

	/**
	 * @param context
	 * @return value of Query
	 */
	public final java.lang.String getQuery(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Query.toString());
	}

	/**
	 * Set value of Query
	 * @param query
	 */
	public final void setQuery(java.lang.String query)
	{
		setQuery(getContext(), query);
	}

	/**
	 * Set value of Query
	 * @param context
	 * @param query
	 */
	public final void setQuery(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String query)
	{
		getMendixObject().setValue(context, MemberNames.Query.toString(), query);
	}

	/**
	 * @return value of Duration
	 */
	public final java.lang.Integer getDuration()
	{
		return getDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of Duration
	 */
	public final java.lang.Integer getDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Duration.toString());
	}

	/**
	 * Set value of Duration
	 * @param duration
	 */
	public final void setDuration(java.lang.Integer duration)
	{
		setDuration(getContext(), duration);
	}

	/**
	 * Set value of Duration
	 * @param context
	 * @param duration
	 */
	public final void setDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer duration)
	{
		getMendixObject().setValue(context, MemberNames.Duration.toString(), duration);
	}

	/**
	 * @return value of RecordCount
	 */
	public final java.lang.Integer getRecordCount()
	{
		return getRecordCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RecordCount
	 */
	public final java.lang.Integer getRecordCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RecordCount.toString());
	}

	/**
	 * Set value of RecordCount
	 * @param recordcount
	 */
	public final void setRecordCount(java.lang.Integer recordcount)
	{
		setRecordCount(getContext(), recordcount);
	}

	/**
	 * Set value of RecordCount
	 * @param context
	 * @param recordcount
	 */
	public final void setRecordCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer recordcount)
	{
		getMendixObject().setValue(context, MemberNames.RecordCount.toString(), recordcount);
	}

	/**
	 * Get value of HTTPMethod
	 * @param httpmethod
	 */
	public final aiden_interfaces.proxies.ENUM_HTTPMethod getHTTPMethod()
	{
		return getHTTPMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of HTTPMethod
	 */
	public final aiden_interfaces.proxies.ENUM_HTTPMethod getHTTPMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HTTPMethod.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_HTTPMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HTTPMethod
	 * @param httpmethod
	 */
	public final void setHTTPMethod(aiden_interfaces.proxies.ENUM_HTTPMethod httpmethod)
	{
		setHTTPMethod(getContext(), httpmethod);
	}

	/**
	 * Set value of HTTPMethod
	 * @param context
	 * @param httpmethod
	 */
	public final void setHTTPMethod(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_HTTPMethod httpmethod)
	{
		if (httpmethod != null) {
			getMendixObject().setValue(context, MemberNames.HTTPMethod.toString(), httpmethod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HTTPMethod.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionLog_Service
	 */
	public final aiden_interfaces.proxies.Service getTransactionLog_Service() throws com.mendix.core.CoreException
	{
		return getTransactionLog_Service(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionLog_Service
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Service getTransactionLog_Service(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Service result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionLog_Service.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Service.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionLog_Service
	 * @param transactionlog_service
	 */
	public final void setTransactionLog_Service(aiden_interfaces.proxies.Service transactionlog_service)
	{
		setTransactionLog_Service(getContext(), transactionlog_service);
	}

	/**
	 * Set value of TransactionLog_Service
	 * @param context
	 * @param transactionlog_service
	 */
	public final void setTransactionLog_Service(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Service transactionlog_service)
	{
		if (transactionlog_service == null) {
			getMendixObject().setValue(context, MemberNames.TransactionLog_Service.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionLog_Service.toString(), transactionlog_service.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionLog_Transaction
	 */
	public final aiden_interfaces.proxies.Transaction getTransactionLog_Transaction() throws com.mendix.core.CoreException
	{
		return getTransactionLog_Transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionLog_Transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Transaction getTransactionLog_Transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionLog_Transaction.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Transaction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionLog_Transaction
	 * @param transactionlog_transaction
	 */
	public final void setTransactionLog_Transaction(aiden_interfaces.proxies.Transaction transactionlog_transaction)
	{
		setTransactionLog_Transaction(getContext(), transactionlog_transaction);
	}

	/**
	 * Set value of TransactionLog_Transaction
	 * @param context
	 * @param transactionlog_transaction
	 */
	public final void setTransactionLog_Transaction(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Transaction transactionlog_transaction)
	{
		if (transactionlog_transaction == null) {
			getMendixObject().setValue(context, MemberNames.TransactionLog_Transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionLog_Transaction.toString(), transactionlog_transaction.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionLogMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.TransactionLog that = (aiden_interfaces.proxies.TransactionLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
