// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies;

public class ViewHostOverview implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject viewHostOverviewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Aiden_Interfaces.ViewHostOverview";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Description("Description"),
		ServiceType("ServiceType"),
		Environment("Environment"),
		ServiceCount("ServiceCount"),
		ViewHostOverview_Host("Aiden_Interfaces.ViewHostOverview_Host"),
		ViewHostOverview_Environment("Aiden_Interfaces.ViewHostOverview_Environment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ViewHostOverview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ViewHostOverview(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject viewHostOverviewMendixObject)
	{
		if (viewHostOverviewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!viewHostOverviewMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.viewHostOverviewMendixObject = viewHostOverviewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aiden_interfaces.proxies.ViewHostOverview initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aiden_interfaces.proxies.ViewHostOverview(context, mendixObject);
	}

	public static aiden_interfaces.proxies.ViewHostOverview load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aiden_interfaces.proxies.ViewHostOverview.initialize(context, mendixObject);
	}

	public static java.util.List<aiden_interfaces.proxies.ViewHostOverview> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> aiden_interfaces.proxies.ViewHostOverview.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Get value of ServiceType
	 * @param servicetype
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType()
	{
		return getServiceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceType
	 */
	public final aiden_interfaces.proxies.ENUM_ServiceType getServiceType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ServiceType.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_ServiceType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ServiceType
	 * @param servicetype
	 */
	public final void setServiceType(aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		setServiceType(getContext(), servicetype);
	}

	/**
	 * Set value of ServiceType
	 * @param context
	 * @param servicetype
	 */
	public final void setServiceType(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_ServiceType servicetype)
	{
		if (servicetype != null) {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), servicetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ServiceType.toString(), null);
		}
	}

	/**
	 * Get value of Environment
	 * @param environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final aiden_interfaces.proxies.ENUM_Environment getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Environment.toString());
		if (obj == null) {
			return null;
		}
		return aiden_interfaces.proxies.ENUM_Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(aiden_interfaces.proxies.ENUM_Environment environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.ENUM_Environment environment)
	{
		if (environment != null) {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), environment.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Environment.toString(), null);
		}
	}

	/**
	 * @return value of ServiceCount
	 */
	public final java.lang.Integer getServiceCount()
	{
		return getServiceCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceCount
	 */
	public final java.lang.Integer getServiceCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ServiceCount.toString());
	}

	/**
	 * Set value of ServiceCount
	 * @param servicecount
	 */
	public final void setServiceCount(java.lang.Integer servicecount)
	{
		setServiceCount(getContext(), servicecount);
	}

	/**
	 * Set value of ServiceCount
	 * @param context
	 * @param servicecount
	 */
	public final void setServiceCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer servicecount)
	{
		getMendixObject().setValue(context, MemberNames.ServiceCount.toString(), servicecount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ViewHostOverview_Host
	 */
	public final aiden_interfaces.proxies.Host getViewHostOverview_Host() throws com.mendix.core.CoreException
	{
		return getViewHostOverview_Host(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewHostOverview_Host
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Host getViewHostOverview_Host(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Host result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ViewHostOverview_Host.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Host.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ViewHostOverview_Host
	 * @param viewhostoverview_host
	 */
	public final void setViewHostOverview_Host(aiden_interfaces.proxies.Host viewhostoverview_host)
	{
		setViewHostOverview_Host(getContext(), viewhostoverview_host);
	}

	/**
	 * Set value of ViewHostOverview_Host
	 * @param context
	 * @param viewhostoverview_host
	 */
	public final void setViewHostOverview_Host(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Host viewhostoverview_host)
	{
		if (viewhostoverview_host == null) {
			getMendixObject().setValue(context, MemberNames.ViewHostOverview_Host.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ViewHostOverview_Host.toString(), viewhostoverview_host.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ViewHostOverview_Environment
	 */
	public final aiden_interfaces.proxies.Environment getViewHostOverview_Environment() throws com.mendix.core.CoreException
	{
		return getViewHostOverview_Environment(getContext());
	}

	/**
	 * @param context
	 * @return value of ViewHostOverview_Environment
	 * @throws com.mendix.core.CoreException
	 */
	public final aiden_interfaces.proxies.Environment getViewHostOverview_Environment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		aiden_interfaces.proxies.Environment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ViewHostOverview_Environment.toString());
		if (identifier != null) {
			result = aiden_interfaces.proxies.Environment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ViewHostOverview_Environment
	 * @param viewhostoverview_environment
	 */
	public final void setViewHostOverview_Environment(aiden_interfaces.proxies.Environment viewhostoverview_environment)
	{
		setViewHostOverview_Environment(getContext(), viewhostoverview_environment);
	}

	/**
	 * Set value of ViewHostOverview_Environment
	 * @param context
	 * @param viewhostoverview_environment
	 */
	public final void setViewHostOverview_Environment(com.mendix.systemwideinterfaces.core.IContext context, aiden_interfaces.proxies.Environment viewhostoverview_environment)
	{
		if (viewhostoverview_environment == null) {
			getMendixObject().setValue(context, MemberNames.ViewHostOverview_Environment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ViewHostOverview_Environment.toString(), viewhostoverview_environment.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return viewHostOverviewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aiden_interfaces.proxies.ViewHostOverview that = (aiden_interfaces.proxies.ViewHostOverview) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
