// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace("b4a536fb-242e-409a-8f21-5727e6b6f673"),
	Debug("6c5fd440-28ff-42aa-925a-3e89249fb750"),
	Info("76f866af-3db2-453b-9bef-3423f52b2168"),
	Warning("71518921-2ade-47d0-aefc-0eedd7536ff7"),
	Error("4b8a40ca-3412-4495-94cf-e55895c4869b"),
	Critical("1d77740b-c705-4cd7-b6b1-23366dd73248");

	private final java.lang.String i18nCaptionKey;
	
	private LogLevel(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
