// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS("c3f0bf5e-ba18-4394-91b6-3fbf769ca0d0"),
	FORMATTING("b16cd249-21f8-421e-a1e6-38e8a210f085"),
	IMAGES("d3e467fc-d8b3-4003-8f9f-a5146ebab8af"),
	LINKS("51b72d66-be3b-4d98-be12-2486b181b9bd"),
	STYLES("f5dbe4dc-236b-41ae-afff-b83f4460582c"),
	TABLES("95b596b3-ddec-46ff-ba56-57c41fc68309");

	private final java.lang.String i18nCaptionKey;
	
	private SanitizerPolicy(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
