// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum StandardEncodings
{
	US_ASCII("2b8f6cc9-58f0-4ba8-9b51-dd6540a08c55"),
	ISO_8859_1("caadcebf-a680-422b-a764-8dd580c2b64c"),
	UTF_8("3694bac4-b0d9-4086-af24-b4619943dd56"),
	UTF_16BE("4e345d7f-3c23-4516-8088-b7ac0b8c3ca6"),
	UTF_16LE("d272dbf4-5877-496d-997e-4b07c95a6cc8"),
	UTF_16("f454605e-05af-4cec-9b2e-3d2d7cda4407");

	private final java.lang.String i18nCaptionKey;
	
	private StandardEncodings(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
