// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testresizevirtualscrolldatagrid.proxies;

public class ContainerSizeHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject containerSizeHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestResizeVirtualScrollDataGrid.ContainerSizeHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CurrentHeight("CurrentHeight");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContainerSizeHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContainerSizeHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject containerSizeHelperMendixObject)
	{
		if (containerSizeHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!containerSizeHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.containerSizeHelperMendixObject = containerSizeHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper(context, mendixObject);
	}

	public static testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of CurrentHeight
	 */
	public final java.lang.Integer getCurrentHeight()
	{
		return getCurrentHeight(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentHeight
	 */
	public final java.lang.Integer getCurrentHeight(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CurrentHeight.toString());
	}

	/**
	 * Set value of CurrentHeight
	 * @param currentheight
	 */
	public final void setCurrentHeight(java.lang.Integer currentheight)
	{
		setCurrentHeight(getContext(), currentheight);
	}

	/**
	 * Set value of CurrentHeight
	 * @param context
	 * @param currentheight
	 */
	public final void setCurrentHeight(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer currentheight)
	{
		getMendixObject().setValue(context, MemberNames.CurrentHeight.toString(), currentheight);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return containerSizeHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper that = (testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
