// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aiden_interfaces.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import aiden_interfaces.impl.CustomWebServiceClient;

/**
 * Call a webservice that returns a list response. Set the name of the array element in the response. The result will be a list of NPEs with each holding the XML of a response element
 */
public class CallWebService extends UserAction<IMendixObject>
{
	private final java.lang.String url;
	/** @deprecated use com.mendix.utils.ListUtils.map(headers, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __headers;
	private final java.util.List<system.proxies.HttpHeader> headers;
	private final java.lang.String basicAuthUserID;
	private final java.lang.String basicAuthPassword;
	private final java.lang.String requestBody;
	private final java.lang.String soapAction;
	private final java.lang.Long connectionTimeout;
	private final java.lang.Long requestTimeout;

	public CallWebService(
		IContext context,
		java.lang.String _url,
		java.util.List<IMendixObject> _headers,
		java.lang.String _basicAuthUserID,
		java.lang.String _basicAuthPassword,
		java.lang.String _requestBody,
		java.lang.String _soapAction,
		java.lang.Long _connectionTimeout,
		java.lang.Long _requestTimeout
	)
	{
		super(context);
		this.url = _url;
		this.__headers = _headers;
		this.headers = java.util.Optional.ofNullable(_headers)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(headersElement -> system.proxies.HttpHeader.initialize(getContext(), headersElement))
			.collect(java.util.stream.Collectors.toList());
		this.basicAuthUserID = _basicAuthUserID;
		this.basicAuthPassword = _basicAuthPassword;
		this.requestBody = _requestBody;
		this.soapAction = _soapAction;
		this.connectionTimeout = _connectionTimeout;
		this.requestTimeout = _requestTimeout;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE

		CustomWebServiceClient client = new CustomWebServiceClient();
		
		return client.callWebService(url, headers, basicAuthUserID, basicAuthPassword, requestBody, soapAction, connectionTimeout, requestTimeout);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CallWebService";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
