// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aiden_interfaces.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import aiden_interfaces.impl.AzureLogAnalyticsSigner;

public class CreateAzureLogAnalyticsSignature extends UserAction<java.lang.String>
{
	private final java.lang.String primaryKey;
	private final java.lang.String stringToSign;

	public CreateAzureLogAnalyticsSignature(
		IContext context,
		java.lang.String _primaryKey,
		java.lang.String _stringToSign
	)
	{
		super(context);
		this.primaryKey = _primaryKey;
		this.stringToSign = _stringToSign;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		return AzureLogAnalyticsSigner.buildSignature(primaryKey, stringToSign);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateAzureLogAnalyticsSignature";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
