// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aiden_interfaces.actions;

import java.util.ArrayList;
import java.util.List;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import aiden_interfaces.proxies.JsonArrayElement;

public class SplitJsonArray extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String json;

	public SplitJsonArray(
		IContext context,
		java.lang.String _json
	)
	{
		super(context);
		this.json = _json;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<IMendixObject> resultList = new ArrayList<IMendixObject>();
		
        JsonArray array = JsonParser.parseString(json).getAsJsonArray();

        for (JsonElement element : array) {
            String elementStr = element.toString();
            JsonArrayElement mxElement = new JsonArrayElement(getContext());
            mxElement.setJSON(elementStr);
            resultList.add(mxElement.getMendixObject());
        }

		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SplitJsonArray";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
