// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aiden_interfaces.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import aiden_interfaces.impl.CustomWebServiceClient;

public class SplitWebServiceListResponse extends UserAction<java.util.List<IMendixObject>>
{
	private final java.lang.String responseBody;
	private final java.lang.String responseElementName;
	private final java.lang.Boolean omitXmlDeclaration;
	private final java.lang.Boolean indentXml;

	public SplitWebServiceListResponse(
		IContext context,
		java.lang.String _responseBody,
		java.lang.String _responseElementName,
		java.lang.Boolean _omitXmlDeclaration,
		java.lang.Boolean _indentXml
	)
	{
		super(context);
		this.responseBody = _responseBody;
		this.responseElementName = _responseElementName;
		this.omitXmlDeclaration = _omitXmlDeclaration;
		this.indentXml = _indentXml;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		CustomWebServiceClient client = new CustomWebServiceClient();
		
		return client.processListResponse(responseBody, responseElementName, omitXmlDeclaration, indentXml);
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SplitWebServiceListResponse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
