// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("48d05c0d-2740-44db-a89a-d3376282d4a3"),
	low("96dec956-a488-4885-aeba-d6d31cea08cb"),
	medium("b4bff4a2-0e78-4834-80cb-a96da9c39182"),
	high("09e128f6-7ee9-4dcf-b9c2-520f6b8b7140"),
	custom("fe656d15-8bd1-40bf-aa26-393ac00a63a6");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
