// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the Aiden_Interfaces module

	/**
	* The part to include in the URL after the workspace ID
	*/
	public static java.lang.String getAZURE_LOG_ANALYTICS_ENDPOINT()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.AZURE_LOG_ANALYTICS_ENDPOINT");
	}

	/**
	* Primary key of the Azure Log Analytics Workspace
	*/
	public static java.lang.String getAZURE_LOG_ANALYTICS_WORKSPACE_PRIMARYKEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.AZURE_LOG_ANALYTICS_WORKSPACE_PRIMARYKEY");
	}

	public static java.lang.String getAZURE_LOGTABLE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.AZURE_LOGTABLE");
	}

	/**
	* ID of the workspace that is linked to Azure Application Insights
	*/
	public static java.lang.String getAZURE_WORKSPACE_ID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.AZURE_WORKSPACE_ID");
	}

	public static java.lang.String getLOGNODE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.LOGNODE");
	}

	public static java.lang.String getLOGNODE_OAUTH_TOKEN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.LOGNODE_OAUTH_TOKEN");
	}
}