// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aiden_interfaces.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the Aiden_Interfaces module

	public static java.lang.String getAZURE_LOG_SERVICE_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.AZURE_LOG_SERVICE_KEY");
	}

	public static java.lang.String getLOGNODE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.LOGNODE");
	}

	public static java.lang.String getLOGNODE_CUSTOM_WEB_SERVICE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.LOGNODE_CUSTOM_WEB_SERVICE");
	}

	public static java.lang.String getLOGNODE_OAUTH_TOKEN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Aiden_Interfaces.LOGNODE_OAUTH_TOKEN");
	}
}