// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package randomuserservice.proxies;

public class ContextHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contextHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RandomUserService.ContextHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RetrieveCount("RetrieveCount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ContextHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ContextHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contextHelperMendixObject)
	{
		if (contextHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!contextHelperMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contextHelperMendixObject = contextHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static randomuserservice.proxies.ContextHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new randomuserservice.proxies.ContextHelper(context, mendixObject);
	}

	public static randomuserservice.proxies.ContextHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return randomuserservice.proxies.ContextHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of RetrieveCount
	 */
	public final java.lang.Integer getRetrieveCount()
	{
		return getRetrieveCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveCount
	 */
	public final java.lang.Integer getRetrieveCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RetrieveCount.toString());
	}

	/**
	 * Set value of RetrieveCount
	 * @param retrievecount
	 */
	public final void setRetrieveCount(java.lang.Integer retrievecount)
	{
		setRetrieveCount(getContext(), retrievecount);
	}

	/**
	 * Set value of RetrieveCount
	 * @param context
	 * @param retrievecount
	 */
	public final void setRetrieveCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer retrievecount)
	{
		getMendixObject().setValue(context, MemberNames.RetrieveCount.toString(), retrievecount);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contextHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final randomuserservice.proxies.ContextHelper that = (randomuserservice.proxies.ContextHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
