// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package randomuserservice.proxies;

public class GetRandomUserResponse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject getRandomUserResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RandomUserService.GetRandomUserResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Seed("Seed"),
		Results("Results"),
		Page("Page"),
		Version("Version");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GetRandomUserResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GetRandomUserResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject getRandomUserResponseMendixObject)
	{
		if (getRandomUserResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!getRandomUserResponseMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.getRandomUserResponseMendixObject = getRandomUserResponseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static randomuserservice.proxies.GetRandomUserResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new randomuserservice.proxies.GetRandomUserResponse(context, mendixObject);
	}

	public static randomuserservice.proxies.GetRandomUserResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return randomuserservice.proxies.GetRandomUserResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of Seed
	 */
	public final java.lang.String getSeed()
	{
		return getSeed(getContext());
	}

	/**
	 * @param context
	 * @return value of Seed
	 */
	public final java.lang.String getSeed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Seed.toString());
	}

	/**
	 * Set value of Seed
	 * @param seed
	 */
	public final void setSeed(java.lang.String seed)
	{
		setSeed(getContext(), seed);
	}

	/**
	 * Set value of Seed
	 * @param context
	 * @param seed
	 */
	public final void setSeed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String seed)
	{
		getMendixObject().setValue(context, MemberNames.Seed.toString(), seed);
	}

	/**
	 * @return value of Results
	 */
	public final java.lang.Integer getResults()
	{
		return getResults(getContext());
	}

	/**
	 * @param context
	 * @return value of Results
	 */
	public final java.lang.Integer getResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Results.toString());
	}

	/**
	 * Set value of Results
	 * @param results
	 */
	public final void setResults(java.lang.Integer results)
	{
		setResults(getContext(), results);
	}

	/**
	 * Set value of Results
	 * @param context
	 * @param results
	 */
	public final void setResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer results)
	{
		getMendixObject().setValue(context, MemberNames.Results.toString(), results);
	}

	/**
	 * @return value of Page
	 */
	public final java.lang.Integer getPage()
	{
		return getPage(getContext());
	}

	/**
	 * @param context
	 * @return value of Page
	 */
	public final java.lang.Integer getPage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Page.toString());
	}

	/**
	 * Set value of Page
	 * @param page
	 */
	public final void setPage(java.lang.Integer page)
	{
		setPage(getContext(), page);
	}

	/**
	 * Set value of Page
	 * @param context
	 * @param page
	 */
	public final void setPage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer page)
	{
		getMendixObject().setValue(context, MemberNames.Page.toString(), page);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.String getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.String getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.String version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return getRandomUserResponseMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final randomuserservice.proxies.GetRandomUserResponse that = (randomuserservice.proxies.GetRandomUserResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
