// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("5b416dde-35e4-4e80-a3f5-40c9becb135b"),
	Geocodio("d5e0c600-2c46-42d2-b896-11a32b397191"),
	LocationIQ("7798b59b-7a27-4b0c-aac3-e7e381b71f7f"),
	MapQuest("a3f7df60-4b21-4db1-8ee2-7bec7c753d98");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
