// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public enum ENUM_ScheduleType
{
	Single("c5184811-0eea-47f4-9d94-ce6401155304"),
	Multiple("b49b291d-549b-4c5d-bc77-7e9f5ba11c6c");

	private final java.lang.String i18nCaptionKey;
	
	private ENUM_ScheduleType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
