// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmodule.proxies;

public class Person implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestModule.Person";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		PersonID("PersonID"),
		Email("Email"),
		Phone("Phone"),
		Birthdate("Birthdate"),
		Tasks("Tasks"),
		City("City"),
		State("State"),
		Postcode("Postcode"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		StreetName("StreetName"),
		Housenumber("Housenumber"),
		Person_Country("TestModule.Person_Country"),
		Person_TimeZone("TestModule.Person_TimeZone"),
		Person_Language("TestModule.Person_Language");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Person(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Person(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personMendixObject)
	{
		if (personMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!personMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.personMendixObject = personMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testmodule.proxies.Person initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmodule.proxies.Person(context, mendixObject);
	}

	public static testmodule.proxies.Person load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmodule.proxies.Person.initialize(context, mendixObject);
	}

	public static java.util.List<testmodule.proxies.Person> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> testmodule.proxies.Person.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of PersonID
	 */
	public final java.lang.Long getPersonID()
	{
		return getPersonID(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonID
	 */
	public final java.lang.Long getPersonID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.PersonID.toString());
	}

	/**
	 * Set value of PersonID
	 * @param personid
	 */
	public final void setPersonID(java.lang.Long personid)
	{
		setPersonID(getContext(), personid);
	}

	/**
	 * Set value of PersonID
	 * @param context
	 * @param personid
	 */
	public final void setPersonID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long personid)
	{
		getMendixObject().setValue(context, MemberNames.PersonID.toString(), personid);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Birthdate
	 */
	public final java.util.Date getBirthdate()
	{
		return getBirthdate(getContext());
	}

	/**
	 * @param context
	 * @return value of Birthdate
	 */
	public final java.util.Date getBirthdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Birthdate.toString());
	}

	/**
	 * Set value of Birthdate
	 * @param birthdate
	 */
	public final void setBirthdate(java.util.Date birthdate)
	{
		setBirthdate(getContext(), birthdate);
	}

	/**
	 * Set value of Birthdate
	 * @param context
	 * @param birthdate
	 */
	public final void setBirthdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date birthdate)
	{
		getMendixObject().setValue(context, MemberNames.Birthdate.toString(), birthdate);
	}

	/**
	 * @return value of Tasks
	 */
	public final java.lang.Boolean getTasks()
	{
		return getTasks(getContext());
	}

	/**
	 * @param context
	 * @return value of Tasks
	 */
	public final java.lang.Boolean getTasks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Tasks.toString());
	}

	/**
	 * Set value of Tasks
	 * @param tasks
	 */
	public final void setTasks(java.lang.Boolean tasks)
	{
		setTasks(getContext(), tasks);
	}

	/**
	 * Set value of Tasks
	 * @param context
	 * @param tasks
	 */
	public final void setTasks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tasks)
	{
		getMendixObject().setValue(context, MemberNames.Tasks.toString(), tasks);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of State
	 */
	public final java.lang.String getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final java.lang.String getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.State.toString());
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(java.lang.String state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String state)
	{
		getMendixObject().setValue(context, MemberNames.State.toString(), state);
	}

	/**
	 * @return value of Postcode
	 */
	public final java.lang.String getPostcode()
	{
		return getPostcode(getContext());
	}

	/**
	 * @param context
	 * @return value of Postcode
	 */
	public final java.lang.String getPostcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Postcode.toString());
	}

	/**
	 * Set value of Postcode
	 * @param postcode
	 */
	public final void setPostcode(java.lang.String postcode)
	{
		setPostcode(getContext(), postcode);
	}

	/**
	 * Set value of Postcode
	 * @param context
	 * @param postcode
	 */
	public final void setPostcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String postcode)
	{
		getMendixObject().setValue(context, MemberNames.Postcode.toString(), postcode);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.math.BigDecimal getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.math.BigDecimal latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.math.BigDecimal getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.math.BigDecimal longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of StreetName
	 */
	public final java.lang.String getStreetName()
	{
		return getStreetName(getContext());
	}

	/**
	 * @param context
	 * @return value of StreetName
	 */
	public final java.lang.String getStreetName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StreetName.toString());
	}

	/**
	 * Set value of StreetName
	 * @param streetname
	 */
	public final void setStreetName(java.lang.String streetname)
	{
		setStreetName(getContext(), streetname);
	}

	/**
	 * Set value of StreetName
	 * @param context
	 * @param streetname
	 */
	public final void setStreetName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String streetname)
	{
		getMendixObject().setValue(context, MemberNames.StreetName.toString(), streetname);
	}

	/**
	 * @return value of Housenumber
	 */
	public final java.lang.Integer getHousenumber()
	{
		return getHousenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Housenumber
	 */
	public final java.lang.Integer getHousenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Housenumber.toString());
	}

	/**
	 * Set value of Housenumber
	 * @param housenumber
	 */
	public final void setHousenumber(java.lang.Integer housenumber)
	{
		setHousenumber(getContext(), housenumber);
	}

	/**
	 * Set value of Housenumber
	 * @param context
	 * @param housenumber
	 */
	public final void setHousenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer housenumber)
	{
		getMendixObject().setValue(context, MemberNames.Housenumber.toString(), housenumber);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Person_Country
	 */
	public final testmodule.proxies.Country getPerson_Country() throws com.mendix.core.CoreException
	{
		return getPerson_Country(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_Country
	 * @throws com.mendix.core.CoreException
	 */
	public final testmodule.proxies.Country getPerson_Country(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testmodule.proxies.Country result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_Country.toString());
		if (identifier != null) {
			result = testmodule.proxies.Country.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Person_Country
	 * @param person_country
	 */
	public final void setPerson_Country(testmodule.proxies.Country person_country)
	{
		setPerson_Country(getContext(), person_country);
	}

	/**
	 * Set value of Person_Country
	 * @param context
	 * @param person_country
	 */
	public final void setPerson_Country(com.mendix.systemwideinterfaces.core.IContext context, testmodule.proxies.Country person_country)
	{
		if (person_country == null) {
			getMendixObject().setValue(context, MemberNames.Person_Country.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Person_Country.toString(), person_country.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Person_TimeZone
	 */
	public final system.proxies.TimeZone getPerson_TimeZone() throws com.mendix.core.CoreException
	{
		return getPerson_TimeZone(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_TimeZone
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.TimeZone getPerson_TimeZone(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.TimeZone result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Person_TimeZone.toString());
		if (identifier != null) {
			result = system.proxies.TimeZone.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Person_TimeZone
	 * @param person_timezone
	 */
	public final void setPerson_TimeZone(system.proxies.TimeZone person_timezone)
	{
		setPerson_TimeZone(getContext(), person_timezone);
	}

	/**
	 * Set value of Person_TimeZone
	 * @param context
	 * @param person_timezone
	 */
	public final void setPerson_TimeZone(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.TimeZone person_timezone)
	{
		if (person_timezone == null) {
			getMendixObject().setValue(context, MemberNames.Person_TimeZone.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Person_TimeZone.toString(), person_timezone.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Person_Language
	 */
	public final java.util.List<system.proxies.Language> getPerson_Language() throws com.mendix.core.CoreException
	{
		return getPerson_Language(getContext());
	}

	/**
	 * @param context
	 * @return value of Person_Language
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.Language> getPerson_Language(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.Language> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Person_Language.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.Language.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Person_Language
	 * @param person_language
	 */
	public final void setPerson_Language(java.util.List<system.proxies.Language> person_language)
	{
		setPerson_Language(getContext(), person_language);
	}

	/**
	 * Set value of Person_Language
	 * @param context
	 * @param person_language
	 */
	public final void setPerson_Language(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.Language> person_language)
	{
		var identifiers = person_language
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Person_Language.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmodule.proxies.Person that = (testmodule.proxies.Person) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
