// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("b9945fca-9148-4441-b10e-eeb2487b2042"),
	startsWith("edf1a22e-619e-4859-9070-89276d15a2b3"),
	endsWith("6adbfa72-cdf1-401c-a656-482c370c5a91"),
	between("16247276-c229-47f2-b27b-162c4c7f6d35"),
	greater("b6557fb6-5736-44b3-b7af-50e3bae20e71"),
	greaterEqual("b8ea67cc-b17a-4337-b273-f076d771b54f"),
	equal("b1189296-3d64-4042-b817-db7706c9a19b"),
	notEqual("928122b5-57ca-427b-8404-2dccb791c00e"),
	smaller("47d94a27-ae8f-4ce7-b597-e3889f1a7994"),
	smallerEqual("5c591b14-691c-43f3-a464-db639a5dafe8"),
	empty("1d03c686-985a-4745-8f82-265d8d788ac3"),
	notEmpty("f3cbaed7-9e8d-4025-95dc-5eed154e5814");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
