// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("d153fd18-04a4-49af-9a15-de76abd3db3b"),
	startsWith("7f6a94be-4d83-4f94-9bfc-2754666497a6"),
	endsWith("43d91831-7932-4133-836b-3b0741d52e7a"),
	between("29fa2147-3cef-42fe-948f-e86ec1563fa4"),
	greater("d935c02c-edd9-4136-9223-bfbbd6cdf3ad"),
	greaterEqual("dbe1e12c-a295-4f21-98b6-4580a41c88f7"),
	equal("bf6ca275-0326-46ef-8e5c-330c144cfa68"),
	notEqual("0ddbeb03-cab0-45cb-8b2f-c9f38c927100"),
	smaller("eb59bfc9-03a4-4e9d-a99c-211a2d8cf42b"),
	smallerEqual("04d408f3-6e9c-4a4f-b5ae-4bda8c986da1"),
	empty("7f12f2f8-fa9e-40b1-b4f3-eb7e0649a8cc"),
	notEmpty("4b0bd0b9-da40-4651-a792-43d6cc15a6bb");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
