// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("26054af3-8bee-45e0-999a-529b69a2a2a6"),
	startsWith("1b707575-42a1-4256-8312-ceb8553c7500"),
	endsWith("1a92f3f1-3049-4102-91ff-482e4aa8ec0e"),
	between("1dc18c32-a0b0-44e1-9a1a-5a35a1479652"),
	greater("40290ac8-3a00-428d-9626-dbeeecadf9b2"),
	greaterEqual("9a0fb990-8420-432f-b449-734b2ff1bd10"),
	equal("6f435be7-ea11-4b27-bd08-e3d1087b26eb"),
	notEqual("c05f6bde-cd92-4294-b0a0-9b4067ee0637"),
	smaller("914285a3-4b57-4062-874a-d6e3454954c6"),
	smallerEqual("5e4c0f64-fe90-434d-8b56-9291e9da7304"),
	empty("0c27a7e8-a5a7-47f8-926b-8049f0808208"),
	notEmpty("716b1a2c-672b-45a4-9fb3-4ed89f62d938");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
