// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testresizevirtualscrolldatagrid.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestResizeVirtualScrollDataGrid module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ContainerSizeHelperBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestResizeVirtualScrollDataGrid.DS_ContainerSizeHelper");
		return builder;
	}

	public static testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper dS_ContainerSizeHelper(IContext context)
	{
		Object result = dS_ContainerSizeHelperBuilder().execute(context);
		return result == null ? null : testresizevirtualscrolldatagrid.proxies.ContainerSizeHelper.initialize(context, (IMendixObject) result);
	}
}
